image:
  repository: msdemo/customerapi
  tag: latest

service: 
  port: 8080
 

livenessProbe:
  httpGet:
    path: /api/v1/customerapi/health
    port: 8080
    initialDelaySeconds: 3
    periodSeconds: 3

readinessProbe:
  httpGet:
    path: /api/v1/customerapi/health
    port: 8080
    initialDelaySeconds: 3
    periodSeconds: 3    