{{- if .Values.ingress.enabled -}}

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: node-k8s-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - backend:
          service:
            name: order-service-node-k8s
            port: 
              number: 8080
        path: /order-service(/|$)(.*)
        pathType: Prefix
      - backend:
          service:
            name: customer-service-node-k8s
            port: 
              number: 8080
        path: /customer-service(/|$)(.*)
        pathType: Prefix

{{- end }}        